### ISSUE TITLE
Disable Back Button behavior in Navigation controller

### ISSUE THREAD

**Issue by JigarM** [nicwise/BTProgressHUD#39]
Hi Friends, 
its a great library. 
i have one issue like when i use BTProgressHUD.show(), it will show me the Progress HUD in Whole navigation controller. so, it disable Whole controller with navigation back button behavior for pop the view controller.

if Progress HUD add in the UIViewController then it solves my issue i think.
is it possible to add BTProgressHUD in UIViewController?

**Comment by nicwise** [comment]
Basically, no. You could change the source and make it add it to a UINavController, but you'd need to pass it in, and make sure you release it etc.

Not something I plan to add to the main library.
