### ISSUE TITLE
Cancel button overlaps progress image without status text

### ISSUE THREAD

**Issue by MichaelRumpler** [nicwise/BTProgressHUD#40]
I want to show the progress image and a Cancel button, but no status message. But the Cancel text overlaps the image. It can easily be reproduced in your BTProgressHUDDemo when you change the status text to null in MainViewController.ViewDidLoad:

			MakeButton("Cancel problem", () =>
				BTProgressHUD.Show("Cancel", () => KillAfter(), null)
				//BTProgressHUD.Show("Cancel", () => KillAfter(), "This is a multilinetext\nSome more text\n more text\n and again more text")
			);

This code brings up a HUD like this:

![image](https://cloud.githubusercontent.com/assets/8309363/9335357/d7f55dde-45d3-11e5-85fa-8de70b70214d.png)

**Comment by nicwise** [comment]
I'll package up a component tonight, but have a look at this one @MichaelRumpler
