### ISSUE TITLE
Progress dialog with wrong colors at the first invocation

### ISSUE THREAD

**Issue by FunThom** [nicwise/BTProgressHUD#44]
Hi Nic,

first of all thanks for your work about BTProgressHUD, it works almost perfect in my Xamarin.Forms app.

I use your component for displaying a progress dialog when synchronizing data from a remote server.
My problem is, that at the first time I invoke the BTProgressHUD with progress information, the 
progress circle will be rendered with wrong colors (iOS). The empty circle is then light grey and it will be filled with white color. After that first call, the progress dialog will be displayed correctly for all further calls (an empty white circle that will be filled with blue color). 

I'm using the latest version 1.19 of the BTProgressHUD component under iOS 9.2 with the latest stable version of  Xamarin 4. The way I invoke the component is like this (I'm using the Xamarin DependencyService to wrap the BTProgressHUD calls):

```
public void ShowProgressHUD(string text, float progressValue)
{
  BTProgressHUD.Show(text, progressValue, ProgressHUD.MaskType.Black);
}

public void DismissProgressHUD()
{
  BTProgressHUD.Dismiss();
}
```

**Comment by FunThom** [comment]
Hi again,

I've found out, that this issue can be fixed with a specific call of the method ```Ring.ResetStyle(...)```.
The method where I call ```ResetStyle``` is ```ShowProgressWorker(...)``` in class ```ProgressHUD```:
```
    void ShowProgressWorker (float progress = -1, string status = null, MaskType maskType = MaskType.None, bool textOnly = false, 
                             ToastPosition toastPosition = ToastPosition.Center, string cancelCaption = null, Action cancelCallback = null, 
                             double timeoutMs = 1000, bool showContinuousProgress = false, UIImage displayContinuousImage = null)
    {

      //----------------------------------------------------------------------------------------------------
      // Author: Thomas Wendling, TWE
      // Date: 2015-12-14      
      Ring.ResetStyle(IsiOS7ForLookAndFeel, (IsiOS7ForLookAndFeel ? TintColor : UIColor.White));
      //----------------------------------------------------------------------------------------------------

      if (OverlayView.Superview == null) {
        var windows = UIApplication.SharedApplication.Windows;
        Array.Reverse (windows);
        foreach (UIWindow window in windows) {
          if (window.WindowLevel == UIWindowLevel.Normal && !window.Hidden) {
            window.AddSubview (OverlayView);
            break;
          }
        }
      }
...
```
That fixed it for me. What is your opinion about that, Nic?

Thanks and best regards,
Thomas

**Comment by nicwise** [comment]
Thanks @FunThom - that looks about right. I've got it in the source now, and I'll push a new version of the component up shortly.

Thanks!

Nic
