### ISSUE TITLE
Xamarin component store vs nuget versioning

### ISSUE THREAD

**Issue by ytn3rd** [nicwise/BTProgressHUD#45]
The current version in Xamarin component store of BTProgressHUD is listed as v1.20, whereas version in nuget is v1.0. I assume this is because it is the first release on nuget so it was called 1.0. 

Should it be changed and have both versioning the same number as to keep them both in line with each other. I assume the current nuget version is the same as the component store version (did not check, but I guess it could even just add the nuget package for you) but it is hard to tell with versioning numbers what one is currently the most up to date version.

**Comment by Redth** [comment]
Nuget is the version to follow. Please disregard the component store.
