### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bennoffsinger** [nicwise/BTProgressHUD#54]
I don't see a license file in your project.  Is this open source and if so, under what license?

**Comment by keithballdotnet** [comment]
Any change on this matter?  Would be nice to know the license?

**Comment by keithballdotnet** [comment]
FYI.  For the next person looking for the license.  You can find it here:

https://github.com/nicwise/BTProgressHUD/blob/master/ComponentStoreAssets/btprogresshud/License.md

**Comment by Redth** [comment]
Added license and notice to the root of the repo for clarification.
