### ISSUE TITLE
iOS 11: Cancel not working 

### ISSUE THREAD

**Issue by jz5** [nicwise/BTProgressHUD#60]
Cancel button on ``BTProgressHUD.Show()`` does not work. The dialog does not disappear when tap. (Or cannot tap the button.)

* iOS 11.0
* Xamarin.iOS: Version 11.0.0.0 
* BTProgressHUD: ver. 1.2.0.5

**Comment by wcoder** [comment]
@Redth, could you look this pull-request?

**Comment by zhangxiongxiong** [comment]
@Redth  could you look this pull-request?
