### ISSUE TITLE
iOS 11 - Appearance Changes

### ISSUE THREAD

**Issue by robert-sayers** [nicwise/BTProgressHUD#67]
Hi, 

I have noticed with the new iOS 11 the position of the Toasts have now changed to be in the centre and the the hud are now appear slightly off centred. I was wondering is there any plans to re-adjust this back to the way it used to be? 

I was wondering is there also a way that you could add the ability to have the hud appear ontop of any window level? 

Many Thanks

**Comment by vchelaru** [comment]
I am saddened to see this project might be dead, and am hoping it's just dormant and @nicwise or @Redth come back and revive it - it's just the best there is on iOS for Xamarin users.

**Comment by nicwise** [comment]
Sorry, this project is LONG dead. Kind of. @Redth took it over about 5 years age (or more), not sure if he's been maintaining it or not.

**Comment by Redth** [comment]
Definitely still will entertain PR's but I don't have much time to actively work on this... Maybe @cheesebaron wants to work on this one too? not sure, he took over working on AndHUD recently...

**Comment by Cheesebaron** [comment]
I'd be happy to help out here too.

**Comment by vchelaru** [comment]
So... @nicwise I get it that you don't work on this anymore, but an unresolved issue is an unresolved issue, so why was it closed?

Anyway, for anyone else who wanders here, I've had a ton of luck getting around this and a bunch of other issues by rolling my own spinner and using the popup library here:

https://github.com/rotorgames/Rg.Plugins.Popup

**Comment by nicwise** [comment]
@Cheesebaron happy to move it to an org - set one up and add me in, and I'll shift it over :)
